env:
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react/recommended
    - plugin:react-hooks/recommended
    - prettier
    - plugin:react/jsx-runtime
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - "@typescript-eslint"
    - react
    - react-native
    - simple-import-sort
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - never
    react/prop-types: off
    "@typescript-eslint/no-namespace": off
    simple-import-sort/imports:
        - error
        - groups:
              - ["^react"]
              - ["^\\u0000"]
              - ["^node:"]
              - ["^"]
              - ["^@?\\w"]
              - ["^@own"]
              - ["^\\."]
    simple-import-sort/exports:
        - error
settings:
    react:
        version: "detect"
